### ISSUE TITLE
Error when start bot

### ISSUE THREAD

**Issue by script-sys** [akasakaid/matchquesttod#5]
Traceback (most recent call last):
  File "/root/matchquesttod/bot.py", line 541, in <module>
    asyncio.run(main())
  File "/root/.pyenv/versions/3.11.9/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/root/.pyenv/versions/3.11.9/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.pyenv/versions/3.11.9/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/root/matchquesttod/bot.py", line 528, in main
    result = await matchq.start()
             ^^^^^^^^^^^^^^^^^^^^
  File "/root/matchquesttod/bot.py", line 210, in start
    token = await self.login()
            ^^^^^^^^^^^^^^^^^^
  File "/root/matchquesttod/bot.py", line 169, in login
    res = await self.http(login_url, self.headers, json.dumps(login_data))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/matchquesttod/bot.py", line 92, in http
    logsize = await aiofiles.ospath.getsize(log_file)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/matchquesttod/venv/lib/python3.11/site-packages/aiofiles/ospath.py", line 14, in run
    return await loop.run_in_executor(executor, pfunc)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.pyenv/versions/3.11.9/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen genericpath>", line 50, in getsize
FileNotFoundError: [Errno 2] No such file or directory: 'http.log'

<img width="662" alt="image" src="https://github.com/user-attachments/assets/6c22d960-882a-4eeb-9c30-14af53af8111">

what am i missing ? libraries ? I installed the python library with no error.

**Comment by akasakaid** [comment]
Yeah, wait me to next update.
